# 异常处理

## 异常类

Python2在exceptions模块内建了很多的异常类型，通过使用dir函数来查看exceptions中的异常类型，如下：

```python
#!/usr/bin/python27
import exceptions
print dir(exceptions)
'''
===
['ArithmeticError', 'AssertionError', 'AttributeError',
'BaseException', 'BufferError', 'BytesWarning',
'DeprecationWarning', 'EOFError', 'EnvironmentError',
'Exception', 'FloatingPointError', 'FutureWarning',
'GeneratorExit', 'IOError', 'ImportError', 'ImportWarning',
'IndentationError', 'IndexError', 'KeyError',
'KeyboardInterrupt', 'LookupError', 'MemoryError',
'NameError', 'NotImplementedError', 'OSError',
'OverflowError', 'PendingDeprecationWarning',
'ReferenceError', 'RuntimeError', 'RuntimeWarning',
'StandardError', 'StopIteration', 'SyntaxError',
'SyntaxWarning', 'SystemError', 'SystemExit',
'TabError', 'TypeError', 'UnboundLocalError',
'UnicodeDecodeError', 'UnicodeEncodeError',
'UnicodeError', 'UnicodeTranslateError', 'UnicodeWarning',
'UserWarning', 'ValueError', 'Warning',
'ZeroDivisionError', '__doc__', '__name__', '__package__']
'''
```

在python3中它们是全局的。

### 捕获异常和获取异常信息

和C#中的try/catch类似，Python中使用try/except关键字来捕捉异常，如下： 

```python
try:
    print(2/0)
except ZeroDivisionError:
    print('除数不能为0')
```

在一个except语句只捕捉其后声明的异常类型，如果可能会抛出的是其他类型的异常就需要再增加一个except语句了，或者也可以指定一个更通用的异常类型比如：Exception，(也可以不接任何异常和参数直接捕获,但是pycharm会给出一个警告的) 如下： 

```python
try:
    print(2/'0')
except ZeroDivisionError:
    print('除数不能为0')
except Exception:
    print('其他类型异常')
```

每个异常都会有一些异常信息，一般情况下我们应该把这些异常信息记录下来： 

```python
try:
    print(2/'0')
except Exception as e:    # Exception位置也可以放一个错误类元组
    # unsupported operand type(s) for /: 'int' and 'str'
    print(e.args)
```

finally子句和try子句联合使用但是和except语句不同，finally不管try子句内部是否有异常发生，都会执行finally子句内的代码。所有一般情况下，finally自己常常用于关闭文件或者在socket中。 

```python
try:
    print(2/'0')
except (ZeroDivisionError,Exception):
    print('发生了一个异常')
else:
    print('正常得出了计算结果')
finally:
    print('不管是否发生异常都执行')
```

### 抛出异常和自定义异常

Python中的raise关键字用于引发一个异常，基本上和C#和Java中的throw关键字相同，如下所示： 

```python
def ThorwErr():
    raise Exception("抛出一个异常") 
# Exception: 抛出一个异常 
ThorwErr()
```

raise关键字后面是抛出是一个通用的异常类型(Exception)，一般来说抛出的异常越详细越好。    
捕捉到了异常，但是又想重新引发它(传递异常)，可以使用不带参数的raise语句即可： 

```python
 class MuffledCalculator:
     muffled = False
     def calc(self,expr):
         try:
             return eval(expr)
         except ZeroDivisionError:
             if self.muffled:
                 print('Division by zero is illegal')
             else:
                 raise
```

Python中也可以自定义自己的特殊类型的异常，只需要要从Exception类继承(直接或间接)即可

## 断言

assert（断言）用于判断一个表达式，在表达式条件为 false 的时候触发异常

```python
assert expression [, arguments]
```

相当于

```python
if not expression:
    raise AssertionError(arguments)
```

## 警告类

和异常类的exceptions模块一样，警告类型在warnings模块中，    
但是事实上Warning基类是Exception基类的子类。

### 发出警告

```python
import warnings

warnings.warn('使用了已弃用功能', DeprecationWarning)
```

### 忽略警告

调用 `filterwarnings()` 将规则添加到警告过滤器，`simplefilter()`是其简易版。    
调用 `resetwarnings()` 将警告过滤器重置为默认状态。

```python
import warnings
warnings.simplefilter("ignore")
```

### 警告上升为异常

```python
import warnings
warnings.simplefilter("error")
```

## 上下文管理

以下内容可能超出理解，以后请回看。

### with as 语句

在使用内置函数`open()`读写文件的时候需要繁琐的方法来捕获异常：

```python
try:
    f = open('1.txt')
    f.read()
finally:
    if f:
        f.close()
```

大可不必如此，`open()`返回的文件句柄对象实现了上下文管理，只需要：

```python
with open('1.txt') as f:
    f.read()
```

### 实现上下文协议

对任意对象实现上下文管理，可以通过实现魔术方法`__enter__`和`__exit__`

```python
class A():

    def __init__(self, name):
        self.name = name

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        if exc_type:
            print(traceback)
```

`__enter__`和`__exit__`也可以借由内置模块`contextlib`的装饰来实现

```python
from contextlib import contextmanager

@contextmanager
def open_a(name):
    yield A(name)
```

### @closing

如果一个对象没有实现上下文，我们就不能把它用于`with`语句。这个时候，可以用`closing()`来把该对象变为上下文对象

```python
from contextlib import closing
from urllib.request import urlopen

with closing(urlopen('https://www.python.org')) as page:
    for line in page:
        print(line)
```

## 熔断器模式

熔断器模式Circuit Breaker

> 熔断器模式可以防止应用程序不断地尝试执行可能会失败的操作，使得应用程序继续执行而不用等待修正错误，或者浪费CPU时间去等到长时间的超时产生。熔断器模式也可以使应用程序能够诊断错误是否已经修正，如果已经修正，应用程序会再次尝试调用操作。
> 
> 熔断器模式就像是那些容易导致错误的操作的一种代理。这种代理能够记录最近调用发生错误的次数，然后决定使用允许操作继续，或者立即返回错误。
